//
//  Node.swift
//  ICS4U-Culminating
//
//  Created by Vincent Cloutier on 2022-05-25.
//

import Foundation

struct Node: Identifiable, Decodable {
    let id: Int
    let description: String?
    let paragraphs: [String]
    let image: String?
    let edges: [Int]
}

// AS YOU PUT IN THE PARAGRAPHS CAN YOU CHECK TO SEE IF I GOT THE EDGES RIGHT?
// IK INDEX 0 WON'T BE WHAT WE USE FOR THE END BUT FOR NOW IT'S GOOD
let nodes = [
    Node(id: 1, description: nil, paragraphs: ["You are a mountain climber. Three years ago you spent the summer at a climbing school in the mountains of Colorado. Your instructors said that you had natural skills as a climber. You made rapid progress, and by the end of the summer you were leading difficult rock and ice climbs.", "That summer, you became close friends with a boy named Carlos. The two of you made a good climbing team. Last year you and he were chosen to join an international team. The expedition made it to the top of two unclimbed peaks in South America.", "One night on that expedition, the group was seated around the cook tent at the base camp. The expedition leader, Franz, told stories of climbing in the Himalayas, the highest mountains in the world."], image: nil, edges: [2]),
    Node(id: 2, description: nil, paragraphs: [""], image: "IMAGE GOES HERE", edges: [3]),
    Node(id: 3, description: nil, paragraphs: [""], image: "IMAGE GOES HERE", edges: [4]),
    Node(id: 4, description: nil, paragraphs: ["The Himalayas form a great natural wall between India and China, with Nepal tucked in amid the peaks. Everest, K2, and Annapurna are the best-known mountains in the Himalayas. These and many other peaks have been climbed. Stil others lie in remote areas where few humans have gone. There, said Franz, in the high valleys beneath the snowfields, lives the yeti, sometimes called the Abominable Snowman.","\"The yeti is said to be a huge beast.\" Franz tells you, \"perhaps a cross between a gorilla and a human. People cannot agree what it is.\"\n\"Is the yeti dangerous?\" Carlos asked.\nFranz shrugged. \"Some say it is. Other people say the yeti is very gentle.\"","\"Have you ever seen one?\" you inquire.\n\"No. Almost no one has. The best proof of the yeti's existence is a set of very large footprints discovered in the 1950s by a British expedition. No one has ever photographed one that I have heard, Franz answers. But still the stories persist.\""], image: nil, edges: [5]),
    Node(id: 5, description: nil, paragraphs: ["You and Carlos decided then and there to find the vet. When you returned from South America, the two of you raised money from the International Foundation For Research Into Strange Phenomena. Your goal: proof positive that vell exist. You will find and photograph the yeti.", "That is what brings you to Kathmandu, the capital of Nepal. Your problems, though, have already begun. Two days ago Carlos left by helicopter to look over the terrain near Mt. Everest. The helicopter returned without him. The pilot told you that Carlos decided to stay up at the Everest base camp to check out a report that a veti had been seen. He had a radio transmitter, but vou have received no word from him. The weather turned bad and radio communication was interrupted.","You have an appointment to speak with R. N. Runal, the Director of Expeditions and Mountain Research and an authority on the yeti. He knows of your plans. You need his help with official permits for the expedition. He will also have good advice and information. But what about Carlos?"], image: nil, edges: [7, 8]),
    Node(id: 7, description: "Cancel your meeting and search for Carlos", paragraphs: [""], image: nil, edges: [9, 13]),
    Node(id: 9, description: "Search below the base camp in the valley", paragraphs: [""], image: "IMAGE GOES HERE", edges: [15, 20]),
    Node(id: 15, description: "Ignore the message and keep looking for Carlos", paragraphs: [""], image: nil, edges: [32]),
    Node(id: 32, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 20, description: "Obey the message and climb back up", paragraphs: [""], image: nil, edges: [31]),
    Node(id: 31, description: nil, paragraphs: [""], image: nil, edges: [43, 45]),
    Node(id: 43, description: nil, paragraphs: [""], image: nil, edges: [58, 62]),
    Node(id: 58, description: nil, paragraphs: [""], image: nil, edges: [77, 80]),
    Node(id: 77, description: nil, paragraphs: [""], image: nil, edges: [91, 95]),
    Node(id: 91, description: nil, paragraphs: [""], image: nil, edges: [101]),
    Node(id: 101, description: nil, paragraphs: [""], image: nil, edges: [133]),
    Node(id: 133, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 95, description: nil, paragraphs: [""], image: nil, edges: [106]),
    Node(id: 106, description: nil, paragraphs: [""], image: nil, edges: [111]),
    Node(id: 111, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 80, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 62, description: nil, paragraphs: [""], image: nil, edges: [81, 82]),
    Node(id: 81, description: nil, paragraphs: [""], image: nil, edges: [110]),
    Node(id: 110, description: nil, paragraphs: [""], image: nil, edges: [82]),
    Node(id: 82, description: nil, paragraphs: [""], image: nil, edges: [96, 98]),
    Node(id: 96, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 98, description: nil, paragraphs: [""], image: nil, edges: [109]),
    Node(id: 109, description: nil, paragraphs: [""], image: nil, edges: [60]),
    Node(id: 60, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 45, description: nil, paragraphs: [""], image: nil, edges: [55, 57]),
    Node(id: 55, description: nil, paragraphs: [""], image: nil, edges: [76]),
    Node(id: 76, description: nil, paragraphs: [""], image: nil, edges: [78]),
    Node(id: 45, description: nil, paragraphs: [""], image: nil, edges: [55, 57]),
    Node(id: 55, description: nil, paragraphs: [""], image: nil, edges: [76]),
    Node(id: 76, description: nil, paragraphs: [""], image: nil, edges: [78]),
    Node(id: 78, description: nil, paragraphs: [""], image: nil, edges: [100, 102]),
    Node(id: 100, description: nil, paragraphs: [""], image: nil, edges: [104]),
    Node(id: 104, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 102, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 57, description: nil, paragraphs: [""], image: nil, edges: [75]),
    Node(id: 75, description: nil, paragraphs: [""], image: nil, edges: [73]),
    Node(id: 73, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 13, description: "Go above the base camp", paragraphs: [""], image: nil, edges: [14]),
    Node(id: 14, description: nil, paragraphs: [""], image: nil, edges: [22, 23]),
    Node(id: 22, description: nil, paragraphs: [""], image: nil, edges: [34]),
    Node(id: 34, description: nil, paragraphs: [""], image: nil, edges: [21]),
    Node(id: 21, description: nil, paragraphs: [""], image: nil, edges: [46, 47]),
    Node(id: 46, description: nil, paragraphs: [""], image: nil, edges: [59, 64]),
    Node(id: 47, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 59, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 64, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 23, description: nil, paragraphs: [""], image: nil, edges: [33, 38]),
    Node(id: 38, description: nil, paragraphs: [""], image: nil, edges: [50, 48]),
    Node(id: 48, description: nil, paragraphs: [""], image: nil, edges: [49]),
    Node(id: 49, description: nil, paragraphs: [""], image: nil, edges: [68]),
    Node(id: 68, description: nil, paragraphs: [""], image: nil, edges: [69]),
    Node(id: 69, description: nil, paragraphs: [""], image: nil, edges: [88, 89]),
    Node(id: 88, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 89, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 50, description: nil, paragraphs: [""], image: nil, edges: [65, 67]),
    Node(id: 65, description: nil, paragraphs: [""], image: nil, edges: [86, 87]),
    Node(id: 86, description: nil, paragraphs: [""], image: nil, edges: [37, 114]),
    Node(id: 87, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 37, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 114, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 67, description: nil, paragraphs: [""], image: nil, edges: [85, 83]),
    Node(id: 83, description: nil, paragraphs: [""], image: nil, edges: [99]),
    Node(id: 99, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 85, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 8, description: "Go ahead with your plan", paragraphs: [""], image: nil, edges: [10]),
    Node(id: 10, description: nil, paragraphs: [""], image: nil, edges: [16, 19]),
    Node(id: 16, description: nil, paragraphs: [""], image: nil, edges: [24, 27]),
    Node(id: 24, description: nil, paragraphs: [""], image: nil, edges: [26]),
    Node(id: 26, description: nil, paragraphs: [""], image: nil, edges: [40, 116]),
    Node(id: 40, description: nil, paragraphs: [""], image: nil, edges: [51, 63]),
    Node(id: 63, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 51, description: nil, paragraphs: [""], image: nil, edges: [70, 72]),
    Node(id: 70, description: nil, paragraphs: [""], image: nil, edges: [90, 92]),
    Node(id: 90, description: nil, paragraphs: [""], image: nil, edges: [92]),
    Node(id: 92, description: nil, paragraphs: [""], image: nil, edges: [97]),
    Node(id: 97, description: nil, paragraphs: [""], image: nil, edges: [112]),
    Node(id: 112, description: nil, paragraphs: [""], image: nil, edges: [113]),
    Node(id: 113, description: nil, paragraphs: [""], image: nil, edges: [107]),
    Node(id: 107, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 72, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 116, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 27, description: nil, paragraphs: [""], image: nil, edges: [39, 42]),
    Node(id: 39, description: nil, paragraphs: [""], image: nil, edges: [52, 54]),
    Node(id: 52, description: nil, paragraphs: [""], image: nil, edges: [24]),
    Node(id: 54, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 19, description: nil, paragraphs: [""], image: nil, edges: [28, 29]),
    Node(id: 28, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 29, description: nil, paragraphs: [""], image: nil, edges: [0]),
]
