//
//  Node.swift
//  ICS4U-Culminating
//
//  Created by Vincent Cloutier on 2022-05-25.
//

import Foundation

struct Node: Identifiable, Decodable {
    let id: Int
    let description: String?
    let paragraphs: [String]
    let image: String?
    let edges: [Int]
}

let nodes = [
    Node(id: 1, description: nil, paragraphs: ["You are a mountain climber. Three years ago you spent the summer at a climbing school in the mountains of Colorado. Your instructors said that you had natural skills as a climber. You made rapid progress, and by the end of the summer you were leading difficult rock and ice climbs.", "That summer, you became close friends with a boy named Carlos. The two of you made a good climbing team. Last year you and he were chosen to join an international team. The expedition made it to the top of two unclimbed peaks in South America.", "One night on that expedition, the group was seated around the cook tent at the base camp. The expedition leader, Franz, told stories of climbing in the Himalayas, the highest mountains in the world."], image: nil, edges: [2]),
    Node(id: 2, description: nil, paragraphs: [""], image: "IMAGE GOES HERE", edges: [3]),
    Node(id: 3, description: nil, paragraphs: [""], image: "IMAGE GOES HERE", edges: [4]),
    Node(id: 4, description: nil, paragraphs: ["The Himalayas form a great natural wall between India and China, with Nepal tucked in amid the peaks. Everest, K2, and Annapurna are the best-known mountains in the Himalayas. These and many other peaks have been climbed. Stil others lie in remote areas where few humans have gone. There, said Franz, in the high valleys beneath the snowfields, lives the yeti, sometimes called the Abominable Snowman.","\"The yeti is said to be a huge beast.\" Franz tells you, \"perhaps a cross between a gorilla and a human. People cannot agree what it is.\"\n\"Is the yeti dangerous?\" Carlos asked.\nFranz shrugged. \"Some say it is. Other people say the yeti is very gentle.\"","\"Have you ever seen one?\" you inquire.\n\"No. Almost no one has. The best proof of the yeti's existence is a set of very large footprints discovered in the 1950s by a British expedition. No one has ever photographed one that I have heard, Franz answers. But still the stories persist.\""], image: nil, edges: [5]),
    Node(id: 5, description: nil, paragraphs: ["You and Carlos decided then and there to find the vet. When you returned from South America, the two of you raised money from the International Foundation For Research Into Strange Phenomena. Your goal: proof positive that vell exist. You will find and photograph the yeti.", "That is what brings you to Kathmandu, the capital of Nepal. Your problems, though, have already begun. Two days ago Carlos left by helicopter to look over the terrain near Mt. Everest. The helicopter returned without him. The pilot told you that Carlos decided to stay up at the Everest base camp to check out a report that a veti had been seen. He had a radio transmitter, but vou have received no word from him. The weather turned bad and radio communication was interrupted.","You have an appointment to speak with R. N. Runal, the Director of Expeditions and Mountain Research and an authority on the yeti. He knows of your plans. You need his help with official permits for the expedition. He will also have good advice and information. But what about Carlos?"], image: nil, edges: [7, 8, 200]),
    Node(id: 7, description: "Cancel your meeting and search for Carlos", paragraphs: [""], image: nil, edges: [9, 13]),
    Node(id: 9, description: "Search below the base camp in the valley", paragraphs: [""], image: "IMAGE GOES HERE", edges: [15, 20]),
    Node(id: 15, description: "Ignore the message and keep looking for Carlos", paragraphs: [""], image: nil, edges: [32]),
    Node(id: 32, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 20, description: "Obey the message and climb back up", paragraphs: [""], image: nil, edges: [31]),
    Node(id: 31, description: nil, paragraphs: [""], image: nil, edges: [43, 45]),
    Node(id: 43, description: nil, paragraphs: [""], image: nil, edges: [58, 62]),
    Node(id: 58, description: nil, paragraphs: [""], image: nil, edges: [77, 80]),
    Node(id: 77, description: nil, paragraphs: ["\"Let's go back!\"", "Runal nods his agreement. This looks too much like a trap. You believe that Carlos left his pack as a warning to you.", "Just as you slip out of the thicket, you see a huge creature, seven or more feet tall, weighing at least two hundred pounds, with short reddish fur covering its body. The creature has an oval, pointed head. Its feet are very wide and long. It sits next to the dead yak, eating.", "You are nearly paralyzed with fear. But this may be your only chance to get a photograph!"], image: nil, edges: [91, 95]),
    Node(id: 91, description: "If you take pictures", paragraphs: ["Runal backs away from the creature. You advance very quietly and ease the lens cap from your digital camera.", "Dropping to one knee you position the camera, framing the yeti and its meal against a backdrop of Lhotse and Everest.", "The digital camera records multiple images of the yeti. The yeti stops eating; his head arches up and around. He sniffs the air. Then he sees you."], image: nil, edges: [101]),
    Node(id: 101, description: nil, paragraphs: ["You freeze. The camera slips out of your hands. The yeti jumps up with a roar and lunges at you. Before you know what has happened, the yeti has you in its grasp.", "Runal leaps forward, swinging the ice axe that he carries as a walking stick. He hits the yeti three times on the shoulders with the flat face of the axe. The blows are as effective as a mosquito bite.", "From out of nowhere comes a sharp whistle-like call, and the yeti suddenly drops you to the ground. You are shocked and unable to move.", "The woman from the house appears."], image: nil, edges: [133]),
    Node(id: 133, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 95, description: "If you retreat into the thicket", paragraphs: ["\"Back into the thicket! Hurry!\"", "You and Runal make a run for it. The yeti is so busy eating that he pays no attention to the noises you two make.", "\"Now what? We can't go back that way, where the yeti is, and we can't go deeper into this thicket where the others are.\"", "As you finish speaking, the bushes in front of you are pushed aside. Three yeti stand before you.", "The largest yeti beckons you to follow. There is no choice but to do what he asks. The other two yeti follow you and Runal. Any avenue of escape is cut off.", "The pine and rhododendron bushes soon give way to a small clearing. At the far side is a smooth rock face perhaps a hundred meters high. On a group of boulders at the base of the rock sit a group of yeti, varying in age and size. Carlos sits with them. He seems to be okay.", "\"Carlos! Hey, Carlos, what's happening?\"", "Carlos holds up his hand and says, \"Listen to what they have to say.\""], image: nil, edges: [106]),
    Node(id: 106, description: nil, paragraphs: ["You and Runal are made to sit in front of the group of yeti. Your guards stand uneasily behind vou. A yeti of medium height, with a grayish tinge to his fur, stands and looks at you.", "\"You wanted to find us. Well, now you have. If you wish, take pictures. If you wish, record our voices. But listen well, listen and learn so that all will benefit.\"", "His voice has a firm yet relaxed quality that erases your fear. Runal is actually smiling. Suddenly, it occurs to you that maybe he knew what was going on all the time.", "The yeti walks slowly around the circle of beings. He stops, looks to the sky and the mountains, and speaks."], image: nil, edges: [111]),
    Node(id: 111, description: nil, paragraphs: ["\"In the beginning of time on this planet, life was difficult but simple. Survival was what held us together. We took the lives of only those things we needed to feed us. Nothing more.\"", "A slight wind moves the branches of the pines. The yeti continues his tale.", "\"Later, people found fire, lived in villages, later small towns, then bigger and bigger cities. They made weapons to hunt and then to protect themselves from animals and others. Then they began to make war on each other. We, the yeti, retreated, wanting none of the war nor the towns. We kept on retreating until there was no place left to go. So here we are, high in the mountains, where we thought we were safe.\"", "\"But you are safe. We mean no harm.\"", "\"Perhaps not you, but there are others who do. Leave us alone. Return to your own lands. If you want cities and war and this thing they call pollution, then live with them or get rid of them. But leave us be.\"", "The group of yeti nods in agreement. The meeting is over, and you, Carlos, and Runal are allowed to leave. You decide not to take pictures or record their voices. You also decide to suggest to the International Foundation For Research Into Strange Phenomena that a better study would be of the so-called civilized world."], image: nil, edges: [0]),
    Node(id: 80, description: nil, paragraphs: ["\"Too wheeet, too wheeet, too toooo.\"", "You have trouble whistling, you are so nervous. Then you repeat the signal, only louder this time.", "\"Too wheeet, too wheeet, too toooo.\"", "There is a sudden crackling of bushes and twigs. You and Runal pull back ready to run for it. Carlos breaks out of the brush, sees you two, and yells, \"Run for it, run for it!\"", "A camera dangles from his neck, and the three of you leap out of the thicket and make for the trail. You keep on going until you can go no further. Between gasps for breath, Carlos tells you that the yeti carried him to the thicket and allowed him to photograph a group of sixteen yeti. They told him that now he had what he needed and that they wanted to be left alone.", "\"Well, why were we invited?\" you ask.", "\"To help me get back, I guess. I had no idea where I was.\"", "You get back to the helicopter and return to Kathmandu with the first pictures the world has ever seen of the yeti. Fame is now yours. It's the beginning of a great career."], image: nil, edges: [0]),
    Node(id: 62, description: nil, paragraphs: [""], image: nil, edges: [81, 82]),
    Node(id: 81, description: nil, paragraphs: ["The door is too scary. Who knows what's behind? The path, at least, is in the open. You scan the rock face, give one last look at the door, and edge off onto the path.", "Within 50 paces you are up against a steep rock cliff. There seems to be no way out. Behind you the path disappears into a maze of trees. You hear the high-pitched call of the yeti, loud and mocking.", "A crackling sound makes you look up. A huge avalanche thunders down at more than 200 mph."], image: nil, edges: [110]),
    Node(id: 110, description: nil, paragraphs: ["You huddle against the rock wall. The avalanche thunders by. Miraculously, you escape unharmed, except for choking on the snow crystals in the air. Maybe you should get out now and go back to the red door."], image: nil, edges: [82]),
    Node(id: 82, description: nil, paragraphs: ["With your heart thumping so hard you believe the whole world can hear it, you push the reg door open. Inside is a tunnel with smooth wall illuminated by a gentle rose-colored light. There is no sign of life.", "The tunnel winds on for several meters, and then ends abruptly. You find yourself standing in a long, narrow valley with steep walls leading to high, snow-covered peaks, probably Lhotse and Pumor from the look of them. The valley is warm, filled with flowering plants and trees, well guarded from strong winds.", "A boy of eight or nine sits on a carved bench. He smiles at you and says in English, \"Welcome. We thought you would come. Your friend Carlos is anxious to see you.\"", "\"Where is Carlos?\"", "\"Oh, not far. If you wish to join him, you must agree never to go back to the world you came from. Do you understand?\""], image: nil, edges: [96, 98]),
    Node(id: 96, description: "If you decide to leave", paragraphs: ["It's probably the best decision to leave. Don't look for trouble. But what about Carlos?", "You wait for his return, and you wait and wait and wait and wait . . ."], image: nil, edges: [0]),
    Node(id: 98, description: "If you want to join Carlos", paragraphs: ["You feel confident that once you get to Carlos the two of you can plan an escape. The child, who is dressed in a dark maroon robe similar to that Worn by Buddhist monks, leads you down into the valley. As if by magic, the valley appears as a city of light. Its radiance astounds you. Its brilliance dazzles but does not blind. Your fear fades."], image: nil, edges: [109]),
    Node(id: 109, description: nil, paragraphs: ["With gliding motions, you fly along a pathway. It feels as though you have been there before.", "\"We are here. Please enter.\" The boy points the way to a building that shimmers with light. It reminds you of the Taj Mahal, except it has many more towers, and the main dome is surrounded by hundreds of smaller domes, almost like leaves of a flower.", "You take several steps forward, and then feel the grasping of a force not unlike magnetic force. You are held in the force field for several seconds, and then transported to the innermost room of the building."], image: nil, edges: [60]),
    Node(id: 60, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 45, description: nil, paragraphs: [""], image: nil, edges: [55, 57]),
    Node(id: 55, description: nil, paragraphs: [""], image: nil, edges: [76]),
    Node(id: 76, description: nil, paragraphs: ["You start down the trail, and right before your eyes a round orange-colored mass appears. It hovers near you. It's about the size of a beach ball. ZAP! You are hit by a light beam. It feels as though you are being bathed in warm salt water. It's rather pleasant and removes all fear. You don't want to run or hide from this creature, whatever it is.", "\"Hey, it's cool. I'm not your enemy. I'm not bad. Who are you, or I mean, what are you?\"", "You stand still, and several more of these round glowing blobs gather round you.", "\"Earthling wishes knowledge. Earthling friendly. Release light beam. Sensor indicates Earthling is honest and speaks only truth.\"", "The light beam switches off, and in a way you miss the comfort of its warmth. \"I wish Carlos were here,\" you say. Before your eyes Carlos appears!", "\"Carlos! What's up? Where did you come from? This is weird.\""], image: nil, edges: [78]),
    Node(id: 45, description: nil, paragraphs: [""], image: nil, edges: [55, 57]),
    Node(id: 78, description: nil, paragraphs: ["Carlos smiles at you.", "\"Hey, your wish was granted. That's the way it is with these Movidians. If they like you and believe in you, then your thoughts and wishes become real. I've been with them for the last two days. Up here in the mountains, things seem really clear and easy to understand. These mechanical creatures, well, they are higher beings. They use the mountains as their Earth base.\"", "There is a humming sound, like cats purring. It's coming from the three creatures that Carlos calls Movidians.", "One speaks again in a high, mechanical sounding voice.", "\"Time now for decision. We invite you to come with us to the Planet of the Seas in the Void of the Seven Moons. Will you come?\""], image: nil, edges: [100, 102]),
    Node(id: 100, description: "If you go", paragraphs: ["You and Carlos decide that it's too good an opportunity to pass up. You experience no fear or real hesitation. Maybe that has something to do with the light beam that seemed to wash away fear and doubt.", "The head Movidian hovers near you. You even imagine that it is smiling, in spite of the fact that it has no face.", "\"What do we call you?\" you ask. For a moment, there is just the humming of electrical circuits.", "Then the Movidian answers, \"You may call me Norcoon. I am an X52 Double A, intelligent, mobile activator being. I am head of this advance party. We will call you Earth One and Earth Two.\"", "With a hiss, the creatures sink to the ground, where they sit and glow. Norcoon says, \"Please, it is easier to travel to the Planet of the Seas in the Void of the Seven Moons if you remove your body and let your mind float free.", "You look over at Carlos. What does this creature mean by \"remove your body\"?", "\"How? I mean, we are our bodies,\" says Carlos.", "Norcoon points his light beam at you, and once again you feel the warmth and pleasure you felt before. Fear vanishes and, before you know it, you are free."], image: nil, edges: [104]),
    Node(id: 104, description: nil, paragraphs: ["Pure mind--no matter.", "Norcoon approves, and offers you space aboard his mechanical transporter. Inside the pumpkin shape there is plenty of room for you and Carlos and all your thoughts.", "\"Now, my friends, we are on our way to the Planet of the Seas. It's where all thoughts end up.\"", "You whirl away, confident that one day you will return wiser and better able to help others in a world where the going is rough."], image: nil, edges: [0]),
    Node(id: 102, description: "If you refuse, explaining your mission to search for the yeti", paragraphs: ["\"No, we can't go. We must finish our expedition,\" You feel fear begin to creep back. You don't trust this thing.", "Suddenly three Movidians turn on their light beams. Wham! Carlos is hit with the beam, and he vanishes.", "The head Movidian says, \"Earth creature, don't be foolish. Join us. You will never regret it.\"", "You start moving toward the side of the trail. No fast moves, just slow steps that don't seem to bother these strange creatures. You keep talking the entire time.", "\"Tell me more. I mean, what's it like up on the Planet of the Seas?\"", "\"Oh, it is beautiful. You will like it. It is one of the higher realms. Only successful Earth creatures ever get to go there.\"", "You ask, \"What do you mean successful Earth creatures? What makes Carlos and me so successful?\"", "The Movidian glows a brighter color orange. You reach down, picking up a fist-sized rock, and, in a sweeping move, hurl it at the glowing blob. Just at that point several yeti come running. They are swinging great clubs. They slash rapidly in the air next to the Movidians, dodging the light beams. With a frantic gurgle, followed by a high-speed whoosh, the blobs depart. Carlos reappears and, knowing the yeti are now your allies, the two of you start to learn to communicate with them."], image: nil, edges: [0]),
    Node(id: 57, description: nil, paragraphs: [""], image: nil, edges: [75]),
    Node(id: 75, description: nil, paragraphs: ["Four yeti leap out from behind two huge seracs. You and Runal are captured immediately. The vet's strength is unbelievable. Your arms are held in vise-like grips. They carry you like sacks of rice, up further into the icefall. Finally, you are put down, and there in front of you is the helicopter pilot. He is unharmed. One of the yeti speaks."], image: nil, edges: [73]),
    Node(id: 73, description: nil, paragraphs: ["\"Well, thank you for coming here. We thought it would be nice to study you, and it would have been hard for us to travel to your country.\"", "The yeti laughs a low, long chuckle. The others grin. You look at Runal, at the helicopter pilot, at the surrounding mountains.", "The yeti continues, \"Your friend is safe. He will be brought back to you later. Now we have had enough of you, and we hope you have had enough of us.\" The yeti walk off and disappear into the icefall.", "You find your way back to the smashed helicopter. Carlos is there, unharmed as they said. Your only disappointment is at not getting a picture. It is several days before another helicopter finds you and makes a rescue. Tired, somewhat disappointed, you vow to continue your search for life forms in the remote regions of our planet"], image: nil, edges: [0]),
    Node(id: 13, description: "Go above the base camp", paragraphs: [""], image: nil, edges: [14]),
    Node(id: 14, description: nil, paragraphs: [""], image: nil, edges: [22, 23]),
    Node(id: 22, description: nil, paragraphs: [""], image: nil, edges: [34]),
    Node(id: 34, description: nil, paragraphs: [""], image: nil, edges: [21]),
    Node(id: 21, description: nil, paragraphs: [""], image: nil, edges: [46, 47]),
    Node(id: 46, description: nil, paragraphs: [""], image: nil, edges: [59, 64]),
    Node(id: 47, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 59, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 64, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 23, description: nil, paragraphs: [""], image: nil, edges: [33, 38]),
    Node(id: 38, description: nil, paragraphs: [""], image: nil, edges: [50, 48]),
    Node(id: 48, description: nil, paragraphs: [""], image: nil, edges: [49]),
    Node(id: 49, description: nil, paragraphs: [""], image: nil, edges: [68]),
    Node(id: 68, description: nil, paragraphs: [""], image: nil, edges: [69]),
    Node(id: 69, description: nil, paragraphs: [""], image: nil, edges: [88, 89]),
    Node(id: 88, description: nil, paragraphs: ["You go on into the icefall. The sun turns the Khumbu Icefall into a giant solar furnace. You squint, even though you're wearing your dark glacier goggles. Your down parkas are stuffed in the rucksacks, and you are in shirt sleeves. Sangee leads the way, cautiously skirting the huge, overhanging blocks of ice, constantly probing the snow with his ice axe for a hidden crevasse-sure sign of a dangerous snow bridge.", "You three are linked by a slender red-and-yellow rope that stretches between you.", "Suddenly, with a whoop, three yeti jump from their perch high above you and push a giant ice block. It quivers, and then it begins to tumble, slowly at first, then it picks up speed as it rolls toward you.", "Other seracs start to tumble around you, and you are locked forever in a sea of ice. You didn't even have a chance to see the veti. All that remains is their eerie cry, echoing in the ice-filled valley."], image: nil, edges: [0]),
    Node(id: 89, description: nil, paragraphs: ["\"Let's think about it, Sangee. The icefall is dangerous. The rains have weakened the ice and snow. Maybe it is a warning to us to leave this creature alone?\"", "Sangee nods his head. \"As you wish, bara sahib, as you wish.\"", "That night, all your supplies mysteriously disappear. It is further warning to leave things as they are in these high mountains. The yeti have their own way of life, and they do not want you or anyone else to disturb it. Regretfully you decide to withdraw and leave the yeti to their lives in the high Himalayas. You know that it's the right thing to do."], image: nil, edges: [0]),
    Node(id: 50, description: nil, paragraphs: [""], image: nil, edges: [65, 67]),
    Node(id: 65, description: nil, paragraphs: [""], image: nil, edges: [86, 87]),
    Node(id: 86, description: nil, paragraphs: ["Click! The digital camera flashes with its solar battery-operated strobe.", "What a creature! It's really a yeti! It has a huge, hairy body, a giant head, enormous feet. It is frightened by the strobe, and it spots you. It heads right for you, making awful sounds--half growl, half gurgle."], image: nil, edges: [37, 114]),
    Node(id: 87, description: nil, paragraphs: ["You raise the ice axe. The yeti, with eyes flashing, grabs it from your hands, snaps it as though it were a twig, and hurls it over the cliff. The yeti speaks in controlled tones.", "\"Leave us alone. Your world has enough. If we wanted what you have, your cities, your crimes, your wars, we would join you. But we don't want these things. Leave us alone. This is a warning.", "With that, the yeti leaves. You stand and look at the fleeting figure. What will you tell the International Foundation For Research Into Strange Phenomena?"], image: nil, edges: [0]),
    Node(id: 37, description: "If you run for it", paragraphs: [""], image: nil, edges: [0]),
    Node(id: 114, description: "If you stay put, and fire the camera strobe in hopes of scaring it off", paragraphs: ["The digital camera keeps on flashing its strobe. The veti stops in its tracks, searches frantically for something, a friend perhaps, and then turns and. with amazing speed, vanishes into the night.", "Unfortunately for you, the photos you take on your camera are all black with no picture."], image: nil, edges: [0]),
    Node(id: 67, description: nil, paragraphs: [""], image: nil, edges: [85, 83]),
    Node(id: 83, description: nil, paragraphs: ["\"You go ahead, Sangee. We'll stay here and keep watch.\"", "He vanishes into the dark night. There is no wind, only the silence of mountains and sky and stars. Somewhere in the distance you hear the rumbling sound of water as it flows and drops from the glaciers that embrace Annapurna.", "Carlos says, \"We should go and help them. I feel selfish, sitting here safe and sound.\"", "So near dawn you set off without your guide. The going is rough, and you no longer see the flashes of light. Above you towers Annapurna, with her white flanks of ice and snow. Then the sky lightens and the stars seem to disappear into the pale blue of the sky. Sunlight bursts on Machapuchhre. It seems to explode into gold and silver. Within minutes the light reaches Annapurna.", "You stop for a cold breakfast of cheese and bread, washed down with tea."], image: nil, edges: [99]),
    Node(id: 99, description: nil, paragraphs: ["Soon you are at a vertical wall of rock. Above it you see the face of the ice. Carlos drives the spike in; you both rope up and proceed slowly up the rock. Over the rock, you meet an expanse of firm snow. But under it lies hard, cold ice. On with the crampons. You lead the way, probing carefully with your ice axe to seek out any hidden crevasse. The climb seems endless, and even though you are only five thousand meters up, the air is thin and breathing is hard. By mid-morning the sun is like a blast furnace. It reflects off the ice that surrounds you, and in the thin air the ultraviolet rays burn your skin. You both put white zinc ointment on your noses and lips. You had taken a sight bearing when you saw the flashes, but that was at night. Now, in daylight, it is not easy to be sure just where the flashes came from. But you have a good sense of direction, so you keep going. Near noon, you gain a crest, and then you see it. It's a Pilatus Courier aircraft, one used for mountain flying. It lies in the snow, crumpled like a forgotten toy. The tail section is twisted, but the wings are intact. The engine is buried in the snow. Reaching the plane, you open the cabin door. Huddled in the plane are the pilot and two passengers. One of the passengers is unconscious. You do what you can for the people; later that day a Royal Nepal Airlines helicopter finds you. All is well. It was the right thing to give help in the mountains. Congratulations for a job well done."], image: nil, edges: [0]),
    Node(id: 85, description: nil, paragraphs: ["It takes you most of the night to thread your way down steep, tricky trails to reach the valley floor. Once there, you start up the immense Annapurna, scrambling over rocks and skirting the glacier. It is cold, and the night seems long to the three of you. Several more times you see flickers of light. Now you are sure you have done the right thing. Someone needs help.","Near dawn, Carlos says, \"Stop. I think I see something.\"", "Before your eyes, you see what you had come for. Dancing around a large fire are eleven yeti. You have stumbled into a yeti celebration at the end of the monsoons. You quietly watch, taking pictures and making notes. You have proved, at last, that the yeti really exist.", "Months later in Paris, France at the International Explorers Conference, you and Carlos are given their highest award for your work. Success is both exciting and lonely. Good luck."], image: nil, edges: [0]),
    Node(id: 8, description: "Go ahead with your plan", paragraphs: [""], image: nil, edges: [10]),
    Node(id: 10, description: nil, paragraphs: [""], image: nil, edges: [16, 19]),
    Node(id: 16, description: nil, paragraphs: [""], image: nil, edges: [24, 27]),
    Node(id: 24, description: nil, paragraphs: [""], image: nil, edges: [26]),
    Node(id: 26, description: nil, paragraphs: [""], image: nil, edges: [40, 116]),
    Node(id: 40, description: nil, paragraphs: [""], image: nil, edges: [51, 63]),
    Node(id: 63, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 51, description: nil, paragraphs: [""], image: nil, edges: [70, 72]),
    Node(id: 70, description: nil, paragraphs: ["\"I am ready, Runal. Lead the way.\"", "Runal taps three times on the back of the buddha, near the spot its skull and neck join. It makes a clanging sound like cymbals being struck.", "Awesome! Before you stands a seven-foot-tall being, with broad shoulders and huge feet. His face is gentle and kind. You are not frightened.", "Runal introduces him, \"This is Zodak. He is your special guide. Follow him. He will take you where you must go.\"", "\"Can I say goodbye to Carlos?\"", "\"It is not usual. I do not advise it; it might upset him and you. However, if you wish, go and say farewell.\""], image: nil, edges: [90, 92]),
    Node(id: 90, description: "If you go and bid farewell to Carlos", paragraphs: ["You walk out of the room. The yeti, Zodak, accompanies you. Carlos stands outside, as he was when you left him. He is frozen in time. He can't hear you, nor can you hear him. You have become a part of a different world. You start to realize some of the consequences of your decision to go to Shangri-La.", "You say a quiet goodbye to Carlos, even though he cannot hear you, and follow Zodak back into the monastery."], image: nil, edges: [92]),
    Node(id: 92, description: "If you decide against bidding farewell", paragraphs: ["Zodak motions to you to follow. He takes one giant step into the air. You look with amazement as he hovers a meter off the ground. Then you step up into the air, and you, too, are suspended above the floor of the monastery. You are levitating.", "Whoosh!! The two of you zoom out of the monastery, right through the walls, up into the sky. You travel at unimaginable speeds. You climb at a dizzying pace, until the two of you stand on top of the sharp, icy crest of Mt. Everest. Below you stretch glaciers, mountains, valleys. You see the world from the top.", "Zodak points to a narrow slot near the topmost point of Mt. Everest. He says, \"That is the route to Shangri-La.\" He takes three steps, enters the slot, and disappears from sight."], image: nil, edges: [97]),
    Node(id: 97, description: nil, paragraphs: ["You take one last look at the earth about you. You see the clouds rolling up from the flat, dry plains of the Punjab in India. You see the curve of the earth. You see the contrail of an airplane far to the south.", "You step into the narrow chute. It's warm, glistening with the shine of a metal unknown to you. You hover in space in the narrow metal tube. In truth you are moving at a great speed down through the center of Everest. There is a rose-colored glow around you.", "Where is Zodak? Some guide, you think, leaving me alone. What's next?"], image: nil, edges: [112]),
    Node(id: 112, description: nil, paragraphs: ["With a gentle bump, you come to rest. In front of you is a clear glass door. You push it open. There stands Zodak.", "\"Come. Welcome to Shangri-La.\"", "You walk out into a dark green valley surrounded by low-lying hills. In the distance are high mountains. One of them looks like Everest. You hear music unlike any music you have ever heard before. It is somewhat like the sounds in the monastery, the bells and wind. The sunlight is warm and relaxing."], image: nil, edges: [113]),
    Node(id: 113, description: nil, paragraphs: ["Zodak leads you down a long trail to a seven-story building. It seems to be a fortress, but it is painted white and red and gold. There are no soldiers, no guns, only people who smile and greet you as though you are an old friend.", "It seems so natural. You turn to Zodak, and you get a shock. His form has changed. Now he is the mirror image of you! What does this mean?", "Although you never find out about that, you learn about many things as you stay in the valley. You have the chance to try many activities you could never try before--but only what is available in the valley. You learn to be contented within the limits of the small valley.", "Second thoughts?"], image: nil, edges: [107]),
    Node(id: 107, description: nil, paragraphs: ["One last chance, is that it? Is that what you want? Okay. You're on. Out of the valley of Shangri-La and back to the real world. Is it different? Can you do whatever you want? Can you fulfill your dreams? Can you enjoy your life completely? Or must you be content within limits?"], image: nil, edges: [0]),
    Node(id: 72, description: nil, paragraphs: ["Secret worlds. This is all too scary.", "To your way of thinking, you are not yet ready for this kind of thing. You want to explore the world you live in right now. Maybe Runal is crazy. Maybe he's a kidnapper. You'll never know.", "You can walk out of the monastery, find Carlos, and continue the expedition. That's what you came halfway around the world for, and that's what you intend to do. You collect Carlos from in front of the monastery and continue your search for the yeti.", "Months later you are no closer to success than you were at the start. The yeti are elusive and your funds run out. You tried and tried hard. Your grandfather's words come back to you, \"Everyone has the right to fail. Take chances; live life!\""], image: nil, edges: [0]),
    Node(id: 116, description: nil, paragraphs: ["You look at Runal, you look at the monastery, and you look at Carlos.", "\"No, I'm not ready to accept your offer.\"", "No sooner have you spoken the words than clouds choke the narrow valley. The mountains seem to vanish, and the monastery is swallowed up by darkness. Runal turns his back to you and speaks as if to the wind.", "\"I am very sorry that you cannot accept. Since you do not feel that you can go ahead, the expedition is declared over. All permits are revoked. You must return to Kathmandu and leave the country in twenty-four hours.\"", "The note of finality in Runal's voice tells you that you have no choice whatsoever. Your trip is over."], image: nil, edges: [0]),
    Node(id: 27, description: nil, paragraphs: [""], image: nil, edges: [39, 42]),
    Node(id: 39, description: nil, paragraphs: [""], image: nil, edges: [52, 54]),
    Node(id: 52, description: nil, paragraphs: [""], image: nil, edges: [24]),
    Node(id: 54, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 19, description: nil, paragraphs: [""], image: nil, edges: [28, 29]),
    Node(id: 28, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 29, description: nil, paragraphs: [""], image: nil, edges: [0]),
    Node(id: 103, description: nil, paragraphs: ["The woman speaks rapidly in a tongue neither vou nor Runal can understand. It's more a series of Yow grunts, mixed with high piercing whistles. The yeti seems to become quiet, almost docile. The yeti and the woman disappear into the thicket, leaving the two of you stunned and confused but safe to return to Kathmandu with your pictures.", "Years later you entertain your grandchildren with stories of finding the yeti."], image: nil, edges: [0]),
    
    
    // ALTERNATIVE BRANCH (200 SERIES)
    Node(id: 200, description: "If you take the next flight out of the Himalayas", paragraphs: ["You chose to leave the Himalayas, and your return has been uneventful so far. You feel a bit guilty about your choice but are absolutely famished. As the stewardess pushes her squeaky cart down the aisle, she asks, \"would you like the beef or the veggie option?\""], image: nil, edges: [201, 202]),
    Node(id: 201, description: "If you choose the beef option", paragraphs: ["As you enjoy what is supposed to be Beef Stroganough, the captain announces heavy turbulence, which is regular for this mountainous region. However, shortly after, a loud boom draws your attention to the engine outside your window. As the other passengers on this small plane begin to notice the fire, you realize your aisle is the only one with a parachute."], image: nil, edges: [203, 204]),
    Node(id: 202, description: "If you choose the veggie option", paragraphs: ["As you eat your bland pea soup and ponder if abandoning your friend Carlos was a good idea, you can hear a commotion rising over the hum of the plane’s engines. Shortly after, your neighbour asks for room to enter the aisle, and you begin to feel sick. You spend your flight home surrounded by the remnants of food poisoning, wondering if maybe Carlos’ had a better fate."], image: nil, edges: [0]),
    Node(id: 203, description: "If you choose to abandon the plane and jump", paragraphs: ["After a week of living like a contestant on Naked and Afraid you survive without a scratch, and live the rest of your life unable to find love as you are haunted by the memory of your cowardice."], image: nil, edges: [0]),
    Node(id: 204, description: "If you choose to give the parachute to the pretty girl on the plane", paragraphs: ["Everyone on the plane dies, and she deploys her parachute too late and dies as well. If only a trained mountaineerer had taken it instead..."], image: nil, edges: [0])
    
    // ALTERNATIVE BRANCH (300 SERIES)

]
